# Generated by Django 6.0.2 on 2026-03-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_savedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details_reply',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_reply',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_reply',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
